### PR TITLE
Fix: APP-1540 - Proposal Duration Warnings

### PR DESCRIPTION
**Pull request by Fabricevladimir**
## Description

- Add proper warnings for proposal duration

Task: [APP-1540](https://aragonassociation.atlassian.net/browse/APP-1540)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

[APP-1540]: https://aragonassociation.atlassian.net/browse/APP-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jamesej — CHANGES_REQUESTED** [review]
Hi, seeing the same issue as before in that when you enter an invalid Start Time or Expiration Time (by changing any of the 3 fields in each component) and it's corrected, it resets the timezone to GMT+0. Otherwise looks good.

**Comment by Fabricevladimir** [comment]
> Hi, seeing the same issue as before in that when you enter an invalid Start Time or Expiration Time (by changing any of the 3 fields in each component) and it's corrected, it resets the timezone to GMT+0. Otherwise looks good.

@jamesej Ah, yes, the timezone fix is in another ticket. This one takes care of minor bugs found when QA-ing

**Review by WissenIstNacht — APPROVED** [review]
I think things are generally OK on this one 👍

There is a little issue with one of the copies. The one for an end date that is too short does not mention that the date gets auto-corrected like it does in the start time. Might be nice to add that for consistency.

**Review by jamesej — APPROVED** [review]
OK in that case, all good thanks

**Pull request merged**
