### PR TITLE
GitHub workflow for contract tests, slither and echidna

### PR DESCRIPTION
**Pull request by yuetloo**
this PR uses solc 0.7.6 because of slither issue mentioned here: https://github.com/crytic/slither/issues/808

### CODE REVIEW

**Comment by nivida** [comment]
Thanks Loo! 

I will have a look at this [list](https://consensys.github.io/smart-contract-best-practices/security_tools/) and also at the [remix package](https://www.npmjs.com/package/@remix-project/remix-analyzer) because I really would like to use 0.8.x.

btw. We also should look at the workflows [here](https://github.com/crytic/building-secure-contracts) and [here](https://consensys.net/blog/diligence/the-importance-of-a-multi-layered-smart-contract-security-strategy/?utm_content=182956433&utm_medium=social&utm_source=twitter&hss_channel=tw-3129477561).

**Comment by yuetloo** [comment]
Will Aragon pay for the subscription fee for mythx? I have used this
before, it’s probably one of the best out there.

I briefly looked at remix, I used their ui version, didn’t know they have
npm package.. there’re 473 open issues, which is a bit high in my opinion,
not sure about the quality..


I can try securify next.

I was hoping slither would get back to me about how to run against 0.80+
because I noticed issues opened against solc 0.8.8, so may be I would try
different installation methods or install from their GitHub source..

**Comment by nivida** [comment]
Of course will Aragon pay for those subscription what a question haha :-) 

Cool! Yes, I just thought to share some resources to show you more existing tools. For me is it really important that we have a high standard resp. professional CI/CD pipeline (It is also important to be able to run all of the tools locally).

The end-goal of those workflows and tools for our Solidity code base and of course also the JS code base is to be able to create a quality monitoring dashboard we can have public. This will guarantee a high quality of our code bases.

**Comment by yuetloo** [comment]
closing this as changes merged into https://github.com/aragon/zaragoza/pull/49

**Pull request closed without merging**
