### PR TITLE
fix(APP-2518): Link to proposal in the Finance Page Withdrawal isn't working

### PR DESCRIPTION
**Pull request by Barukimang**
## Description

WIP: see comment below 👇 

Task: [APP-2518](https://aragonassociation.atlassian.net/browse/APP-2518)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have tested my code on the test network.

[APP-2518]: https://aragonassociation.atlassian.net/browse/APP-2518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Barukimang** [comment]
Hej @cgero-eth, there's something with `proposalId` I cannot get my head around, so hope you have a tip for me 😄

This is what a `proposalId` looks like:
 
`0x3e3c5b75ef8c9f3b0e245395a4e64987b92bef81_0xe`

But then when querying it from the Subgraph it became: 
 
`0x3e3c5b75ef8c9f3b0e245395a4e64987b92bef81_0x0e00000000000000000000000000000000000000000000000000000000000000_0xb3b97b0241beba1f85e02db43ad320561c674679ccd89de250a1a514f4d09f58_0xf4`
 
Where it contains:
 
- proposalId: `0x3e3c5b75ef8c9f3b0e245395a4e64987b92bef81_0x0e`
- null address: `00000000000000000000000000000000000000000000000000000000000000`
- transaction hash: `0xb3b97b0241beba1f85e02db43ad320561c674679ccd89de250a1a514f4d09f58`
- an id: `0xf4`

Have not been able to find out where and when exactly the `proposalId` is modified in this way. But because of this revised `proposalId` the Transaction Detail modal cannot fetch the right proposal.

Two questions:

- Do you know where and when it is modified?
- Should it be modified like this, or is it a bug you think?

**Comment by cgero-eth** [comment]
> Hej @cgero-eth, there's something with `proposalId` I cannot get my head around, so hope you have a tip for me 😄
> 
> This is what a `proposalId` looks like:   `0x3e3c5b75ef8c9f3b0e245395a4e64987b92bef81_0xe`
> 
> But then when querying it from the Subgraph it became:    `0x3e3c5b75ef8c9f3b0e245395a4e64987b92bef81_0x0e00000000000000000000000000000000000000000000000000000000000000_0xb3b97b0241beba1f85e02db43ad320561c674679ccd89de250a1a514f4d09f58_0xf4`   Where it contains:  
> 
> * proposalId: `0x3e3c5b75ef8c9f3b0e245395a4e64987b92bef81_0x0e`
> * null address: `00000000000000000000000000000000000000000000000000000000000000`
> * transaction hash: `0xb3b97b0241beba1f85e02db43ad320561c674679ccd89de250a1a514f4d09f58`
> * an id: `0xf4`
> 
> Have not been able to find out where and when exactly the `proposalId` is modified in this way. But because of this revised `proposalId` the Transaction Detail modal cannot fetch the right proposal.
> 
> Two questions:
> 
> * Do you know where and when it is modified?
> * Should it be modified like this, or is it a bug you think?

Hey @Barukimang, looks like there's a method on the SDK to process the proposal ID, we're using it on the `useProposal` hook to fetch the proposals (https://github.com/aragon/app/blob/develop/src/services/aragon-sdk/queries/use-proposal.ts#L46). Not sure why we're handling these two compact/extended variants of the proposal

**Comment by Barukimang** [comment]
Thanks for answer @cgero-eth! Wasn't able to re-compact `proposalId` with an SDK function, so added logic to extract the part of the `proposalId` needed by the `useProposal` hook. All is working great now, for both DAOs with and without ENS name, see image below:

Image
image

**Review by cgero-eth — APPROVED** [review]
LGTM, thanks @Barukimang!

**Pull request merged**
