### PR TITLE
Gasless fix proposal dates

### PR DESCRIPTION
**Pull request by selankon**
## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [APP-0000](https://aragonassociation.atlassian.net/browse/APP-0000)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the test network.

### CODE REVIEW

**Review by jamesej — CHANGES_REQUESTED** [review]
I'm hitting a white screen as soon as I try to create a proposal with a Vocdoni DAO. Top level error is on `createProposal.tsx:154` because `votingSettings` is null. The source of this error is `usePluginClient` returning null. Line 83 appears odd and is showing a type error in VSCode with the second `context` parameter.

**Comment by emmdim** [comment]
> I'm hitting a white screen as soon as I try to create a proposal with a Vocdoni DAO. Top level error is on `createProposal.tsx:154` because `votingSettings` is null. The source of this error is `usePluginClient` returning null. Line 83 appears odd and is showing a type error in VSCode with the second `context` parameter.

This apparently refers to an older version of the branched to be reviewed

**Review by emmdim — APPROVED** [review]

**Review by jamesej — CHANGES_REQUESTED** [review]
Hit a gas fee estimation error, Manos kindly worked out it was 
```
Error Message: InvalidVoteEndDate[1707330495,1707330180]
revert InvalidVoteEndDate({limit: earliestVoteEndDate, actual: voteEndDate});
```
He's pinged @ritmo in the chat about this.

**Comment by emmdim** [comment]
@jamesej  can you please re-test?

**Review by jamesej — APPROVED** [review]
All good now thanks!

**Pull request merged**
