### PR TITLE
Fixes to be able to run Zaragoza web-app locally

### PR DESCRIPTION
**Pull request by Barukimang**

### CODE REVIEW

**Comment by RakeshUP** [comment]
Thanks for the fix @Barukimang. The repo is configured to accept only signed commits and this PR can't be merged as-is. You need to setup GPG before signing commits. More details can be found here https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification


Try `git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD~3` (HEAD~no_of_commits) to retroactively signing the commits after installing GPG and force push the branch

**Comment by Barukimang** [comment]
Welcome @RakeshUP!

Followed the steps you mentioned. Did it work?

**Comment by RakeshUP** [comment]
@Barukimang unfortunately it didn't work. You could check that by going to https://github.com/aragon/zaragoza/pull/169/commits and see if each commit has a green "Verified" tag next to the commit hash. 

If you can't make it work for some reason, I could make a separate PR with your changes(if it's not a problem for you) 😃

**Comment by Barukimang** [comment]
@RakeshUP fixed the issue 😉

**Comment by RakeshUP** [comment]
Hey @Barukimang, there was another PR that had the fix for the build issue that was merged. So will be closing this issue soon. 

Please feel free to contribute to the project and we'll help in any way to work with you and merge your upcoming PR's. 😄

**Comment by Barukimang** [comment]
@RakeshUP sure no worries! Good am setup now ;) Allright will submit PR when I see something

**Pull request closed without merging**
