### PR TITLE
resolve #225: use solidity custom errors

### LINKED ISSUE #225: Use Solidity Custom Errors
[CustomErrors are available since solc 0.8.4](https://blog.soliditylang.org/2021/04/21/custom-errors/), are gas-efficient, make the bytecode smaller, and increase readability.

https://github.com/nomiclabs/hardhat/issues/1428 and https://github.com/ethers-io/ethers.js/issues/1493 support it already, while https://github.com/ChainSafe/web3.js/issues/4235 is working on it.
Because of web3.js, https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2839 is pending.

### PR DESCRIPTION
**Pull request by heueristik**
This feature replaces errors strings by custom errors, as described in #225 in our code.

E.g.,
`string private constant ERROR_CAN_NOT_EXECUTE = "VOTING_CAN_NOT_EXECUTE";`
is replaced by
`error VoteExecutionForbidden(uint256 voteId);`.

Then,
`require(_canExecute(_voteId), ERROR_CAN_NOT_EXECUTE);`
becomes
`if(!_canExecute(_voteId)) revert VoteExecutionForbidden(_voteId);`.

### CODE REVIEW

**Comment by novaknole** [comment]
Thanks for this, Definatelly needed.

A couple of points:

1. There're still `requires` remaining in our contracts. For example - in ACL.sol. Better to search for all `require` and update it the same way.  
2. As a common way, the `error` in the contracts should be put above `contract` keyword, not in the contract itself.  An example - https://docs.soliditylang.org/en/v0.8.12/structure-of-a-contract.html#errors

**Comment by heueristik** [comment]
> Thanks for this, Definatelly needed.
> 
> A couple of points:
> 
> 1. There're still `requires` remaining in our contracts. For example - in ACL.sol. Better to search for all `require` and update it the same way.
> 2. As a common way, the `error` in the contracts should be put above `contract` keyword, not in the contract itself.  An example - https://docs.soliditylang.org/en/v0.8.12/structure-of-a-contract.html#errors

Good points, I will make these changes.

**Review by nivida — CHANGES_REQUESTED** [review]
LGTM! By side of the missing custom errors in those files: 

- ACL
- AdaptiveERC165
- Permissions
- Registry
- MerkleDistributor

I would keep the errors within the contract closure as they are. I saw both "patterns" used when looking at other projects and I personally think it is way cleaner to have it within the closure.

**Review by nivida — APPROVED** [review]
LGTM

**Review by novaknole — APPROVED** [review]

**Pull request merged**
