### PR TITLE
Fix: APP-1319 Remove UTC Field Error after Undo

### PR DESCRIPTION
**Pull request by WissenIstNacht**
## Description

This PR essentially hooks the UTC fields in the Voting Setup Step of proposal creations to the `dateTimeValidator`. This results in a correct inline error on the GUI if an invalid UTC value is set, _as well as a correct removal of that error after a changing it back to a valid value_.

Task: [1319](https://aragonassociation.atlassian.net/browse/APP-1319)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by sepehr2github — APPROVED** [review]
Screenshot 2022-12-13 at 1 29 28 PM

Hey, Thanks Vale for the changes you made, I need a quick confirmation from you, Is this image demonstrates the issue that will be tackled in the following PR? Thanks

**Comment by WissenIstNacht** [comment]
Hey @sepehr2github, yes that's it.

The changes have been amended to this PR though, instead of opening a new one.

**Comment by WissenIstNacht** [comment]
Blocking this waiting for [that](https://github.com/aragon/apps/pull/599)

**Review by RakeshUP — APPROVED** [review]

**Review by sepehr2github — APPROVED** [review]
Thanks!

**Pull request merged**
