### PR TITLE
Fix: Duration in Days breaks proposal creation flow

### PR DESCRIPTION
**Pull request by RakeshUP**
## Description

- Selecting voting duration in Days broke the app in new proposal flow
- Right token value passed to cardProposal component in dashboard's winning option

Task: [APP-1409](https://aragonassociation.atlassian.net/browse/APP-1409)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

### CODE REVIEW

**Review by sepehr2github — APPROVED** [review]
Thanks ;D

**Comment by RakeshUP** [comment]
Fixed the issue @sepehr2github mentioned. Disabling the next button on setup voting step till the endDuration has loaded form the subgraph and we display the end time input fields

**Review by jamesej — APPROVED** [review]
Looks good, works fine! Thanks

**Review by sepehr2github — APPROVED** [review]
Thanks For addressing the issue, LGTM 🚀

**Pull request merged**
