### PR TITLE
Feature: APP-1722 - Multisig DAO - Review Proposal Voting Terminal

### PR DESCRIPTION
**Pull request by Fabricevladimir**
## Description
- maps new proposal data to `VotingTerminal` info tab

~~Please review after #701~~

Task: [APP-1722](https://aragonassociation.atlassian.net/browse/APP-1722)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

[APP-1722]: https://aragonassociation.atlassian.net/browse/APP-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by WissenIstNacht — APPROVED** [review]
Nice, thanks.

One comment (address if it's a quick fix, otherwise ignore). On multisig DAOs, the support threshold is shown on the voting terminal's info tab.

**Review by sepehr2github — APPROVED** [review]
Thanks, Great job 👍

**Comment by Fabricevladimir** [comment]
@WissenIstNacht, when reviewing a proposal or after it has been published?

**Comment by WissenIstNacht** [comment]
@Fabricevladimir when reviewing.

**Pull request merged**
